apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OAUTH2_PAAS_MPA_ALLOWED_URIS: AgB8D9Ks+jWbeoDRZzFwEspDpHeRle2ZkpLlMYnwKyOmLZqGlddOzONF/Hz3bB5d2uHj2a0HhHM9b5TC9Adb0bXsc006/7O5x3mHMWXML8Ri9djC3IweGQCQmWk4wAXuBolDHZu5UPT9AUsOr0jRPLYtw69W+qlPo8JLqA4jXaWdEL/IHcZ1XagkBUggZiR9h+Y6Mppgg+4aThuddhOo2mhD9V4RkVA3eFDj7XIG3CVS91UajqwOSfDXRmf3lm8oV/k4Da9YTT9JcPj+SN+yZYcxlAqYIvJBa1b8iJ69fJvqvEwwvIJGZhpeX2lGOLaiwfE2JtMW5YeKr42ZqXGvgB/h8/TY3e9xdQaZYjCFvZm13ucBZKQ/cwzY2YfwqUseYeBP7cXf9mWqW/dZL2q7sYNKsxZ8ogNCpjn/efi1Ad2Bmmv8Dps3dT0DBkyLiQ8EvuPNZgV5IZBAc2YsE5V5Hq6Plhxfo9J15RpYCFExQ84wVhmK0jkSuVrKQ7fnZR1vfO89nQGy/9WpX27IEkvC9/85cDrm5WCQQLdctke1avzww4lqFQ4ciY4X7GT2gOfMK6tpO1rKey6lMh5B6oxvrDhMGbpokU8D1cLxAA4pZwdwuEzdI9Hut/JKV+fEFbsmjGyl4HNzDRtjGBfEgKccLPOOkjWTo21FZ9hOTiuXa9NAUNjm6PTGjZtrQua95Ru+sKo+V91Pc09j3ZYJYI8MT2ljPdSTzL8U+F2KUe5vLWOoYy3nex91O+g9O1IEqwBGJizrkAU=
    OAUTH2_PAAS_MPA_CLIENT_ID: AgBrQnUqHPIoTZVL66bjI1l6+S+viPseY64LMnY4TW3Tzl/hKAu8cV3i09gGttqF+EY+rYrGBZJm8tsJ5YTCepOq9TxaoOtb5gXboHQ7Tc0jXMMlyS9QetLIACV0htTFBzKOIfp7t0/xl82U+3Ulqvh6/vQKxMpj4X4wu/yX23jGx9Do1nJsICP9vmOGKOvqxQHBSwRzs6ZWEU6u9Sssqf5beZ9iSgGu+kjMpBrN3EX9S5E8YxUg9qNx+mK/6akzRPnO26Kj6Wl3oo6V5por4S8qlN1lerIbJmytnZKjw8Oph9N1TOY9rC+GHUvYRa/8NSvQ30LgBZ8wehNBMfZl8JHP22aF4mlUBkvI85H1cY/XwoAWOVPjYR523xmD1yFH9iStpSubZfyAe+5fg+UIbYx13SfVT7E7l2pQ5MrpF9wITwH7kxPMYBDuBBKiad50ZK+lAhLDAzTjWdq7YeekZc4vc3kUJaksadkfiDJwo6zmHOepz1Pgj6tH320b8u/7SVTLfirjrJ1Ab6SD2b2U1qsp5TYS6J/NWsI/UaVOdvckZcmfmTDtaKIJ+tr17KoFp/JNlzhHHpC1sthfm15cl2GLpVouvDMz3nqjuG+1lccIAHO8ix5FhxEiSQzpTwrmfzPaSZ0fygQPrw9t8XEHNCP2G+IfSTEEEDYN0AQ1E/NjMLWUUp80Oskb+769cvo6apDt5wQ1Ri25lbZJbLWFUjNF58eez0D0C8qv2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
      namespace: ${NAMESPACE}
