apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OAUTH2_PAAS_MPA_ALLOWED_URIS: AgBse668eJlgsZh/Fb4YTn8U3K0Vf2uKcMH71hUiZW5pKboqX2xHpsCT9pv22daWu8eKw6asRCqICmSRtyGypDtKh6n8r25NHSxZwJgsMeE6W/UIHG5+FzcnSTf1NDUTeznhB6ZIdZhj5Cw0Fvam6tbock2HangDHy6SxP+N4U6DfVStJJMkES2ivnOH6/NuulmoBuOv502cU+q746ARxbOQq74jm63mo7yxbLDR7HuvLI9lTFpBGPwMH0wd4ML44iWCREKcy37IpFIq2ReahiJwfPcLQ7BqMAeO4EGJSuhh9Aynj7+IBz9WZAQ0L1LPcB3bY/JxaNTBo5phunjJ9hoFYmz7zz3dHh5CKBw1k7cdwn1RGvB3OrHWqnZvsR6s2rAcpxYSa3BaiqRQavSuK4A4UCxPcch1O9AkUWCia8yCrlzueB26xOgOm8WXLkRhn7shhxISKTHk4xeSc9/++PgZTmMxrHvUAyjN+r/zgZPPMN8ouGBh1yf4an1yGxKt198KJfNUW0Ch9anmE50TCRKJf5JF4YqYcaAslGGFjoM4G58m1MHGO2K/lDs6damuWSq69i/ZG8hv51DPw3GFc/d57qVcmvPl0f+CMT0Kk3MoPA7E64v0rV7FI0W1//CHljJ8+NvEAp7T7GsQXyRNwRKMy+lBfq7ekqOGlANNgof0XEsgxQRw6p/E8VSiKjyTYsc9d6nME3HF8Ng341YWkTAUDHTCMRBkb/f9D010AGqa+D6KAXs4K969YEqt5ByN/DCGXnE=
    OAUTH2_PAAS_MPA_CLIENT_ID: AgBFBUctLSj5FstlMQTfJLv/E+tfBHjDq+GLBWI/z3uiz3gQGVWQTsyslRw/EvPYkPd9VJ9A2Y/0lme87IflBZkIQYOTnE/Fv6CuYzNh2HR5YSzimZEaW8ZAqIHP1JshqLsl4wIr49xhH6vUa45ScCft2bcA/gCJVHs2qM9PyuKG0O7yNZxm+qeVrI255SuOxrSx1Hp7OrC0a4Qtwob1DJOVF4eCC4f6hP4rkRX4Fz1W8IoflGX4fXDGLNPVCDjwWIsoSg7VWIR7zF6pf9u9HnG02rzRPn8Y9cBlcHuP6OwIKTALH2gl5amwotdsPOx7y58xoFyxDsurJ4r5wVIJU/NYLHnoYaxu29x37NdWpSnWe8N3kVu1/BZSLYK086YhqhpzyFGXMYoRKML4+JOVOEGej0wIpIDjdffiV+8SrPaA8eVkufm3qRuGq+/it9YNMuEJv2LpsiEOsVYzOmHuMvFCQiVv6y6do7isyX6FJJe0J2vfCpBwLW0OD6sp1sl7RnKF/oWBHSDBFltdWJ8OlKpPlV2kuQWAKSavCHTztdV5pfEuA6eB/nDLWwrmZAq+8DZDKH8Do2N6SISPqQbG+EnlQ8ywxFPC848rtCheXegkHTPgq7TXjtPIDDFhAVLoOyuABGLNA+f0DV/dkM40zgaVoCVhmbaXmKSflqsTkTCUX0Chv+pBMT9SzraLB0eTsBd39GBrAVUxpvAJlqupIJE0qOvQ6d4RVfes9A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
      namespace: ${NAMESPACE}
