apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-admin-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgBYvz46BStMBCoHJpc/u6QIS9LUvjPXM2CQy/4cQni5nMnZuOioWq+tGykI2c3S5JCWb3o0eUxIFFdyBdJs2qWWIoLlkg+zw2t4Iypua01mLsQbfSgbcHzwiYyyrCHQWHMtmJmVrs9ZH9zc3QGl4ZXElJhFdV2+a9gp80xPdxNokqbGa3r/uqQvHG7wprNhCJYepJbUHU4b8EUBnyVCsgPq5mP3+iD0awIcPdAtDdx6NnQsuUbXyDlt07NnbMpPR3A6kiZvt7oAMTQLhbdT2TxqyVuHZeOMWheLj6F6F9Hx+t0fv3QoQR2spXxHZ/kPzOdybJhgfvmGS+jLBxdyVyLdVxop/zPP18Z0/tvFihiQ8ad1RxTpf2vcJefKn48hj/U423VAKfWjkOa34pm9IqvRKx3650kmPCBjzqpURXxcEXUX084dJ3EA1PWoMmyoX4z/BgBUU6q+ehwp//SdsAxbMMb9P2gsQf8KseqhIK8/csxmfJPCPthtHMs183XO/6Fg+5S7Snv38IGUopZ8TUl2vO2NWv8MXE04rO1hbIyuQQNbAvsuD5eGOLxB8hikh9mJ0YzbVyrLnwNxkiZaxC8SyLHX3fc148cndaj48Mrx5qCMXPNLLWVzMAlMrAZg4YtvQgnExOMLVCZL/4lxd6lWTHzlIQMsPsLFF60jN/Sxqg4jB2z56HsQrRZRbOHFsnGFIq04LChkrMG5H9hux2wIOukBQDeFBqQ=
    USER_ACCOUNT_API_KEY: AgAhF/loorWUROpFxtQGXLdvC8ly5JUYewvs5M3hBaUtX1evfSmj3z2gp5tNsu6YK641GgI2XR6YcWbEYvbzJsZTKcurT9vGnbfCgctB+qBs4ZV/yWvhji3YXBLEPRvlG6fVFRipcR0ABD+BsLILr2xNFz285KQ/lZmD8svWlAjtk+eX2+H1FemkD4RsVlL5KdiLMFR571KIlziMSZbQryhEdjy4hoDd0fPZAMwgp/wQc6nsIEog6772axayEJ5avPeOYBxT61ufVhZzESzrQ9scRrwkiB0OAOeH0N0eHdd8sY+G4AtiONVWxgYrnauuqiAc2V29nZjdNMbX27Ik3khMWbl+svoqrifOjtVcPaoc9hlZ07ETxSq5E4JdK2icGYUyiVPfIb4DLV71vXWFg54PkuHGR/hT5JTgI2qgoNRbl2RTIqty130dRnUpN+3WuY+d+25ZDtxiliKukaNA+p/uZLu2RrJ2QxmqC8ep/k9VaKlVZzY8ahgmWjxKbsGVgLYXazmERK3YXkDTTgFH4YaSTCRI3Y4D0DjEwvWGv1Nz/EaRuD82I7d+ZXjED+fcg6TlhAFoX5cir8Eup9whRPyryAM91z3BGOxsUkzItMiCVy3Dq8uX/6BdpJXB7EONTIvKgh2ILcDJpxB/WXAdTso8ppbwMji1zL3UdsFrozvVnVxoy1oqSZ1bSjejt07StttWqV/zP6vZ3hHWu+8AtrDZzIxgdbVMOl2KpcnLwB8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-admin-secret
      namespace: ${NAMESPACE}
