apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-admin-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgAek9ObR5Tp7EMe0zfFyDDPbrNiy83kW2LgxM+Tp0mCM62laPBEhLvmkD91vv6dNTl+8ksCxK9EnLO5a1bf6W0abbA4pw87ZTL1qIVl9+iHoleGEvwK86MCtwVnWrFnsHGwXXXyFGtpLVRYZdg1ooMMEMsM7RMar3EOcy4finw4XjKispEiaHVtnUpzfY6BLgKjFfnW6rLeuKkw6JmQL8ApLivq426SkQBrxWx3hxTVrOWOBIDsQvQavXbokmvZWrHqKl7RbgNpb0ZNrfYGaSS/+geW+KrYjQemw3KOf8l/e+vOTBY3NMLhoePEEFYLPRicRAfeGaMqgZ/rr1+YyW8YFop+f67mCds/m10YKa6SXKAgZdrsVqk4vZF4S3rmLj0VnsDH76X9zDGNGzdT+00VevDdnlxmJVdJhveicTADdCp6YW3NXmD3v6iSjJJ3/nxTWtMmXBZCLizkjxd6CnRykWQKW9RCFKfPFrbsLgAYJi1CHuhvWC2+rEKnHfxFo7ArSQrOROC4Xk5ruUjgOWG//3zywAn1cReZnJafATFxMccjaDlCJPANN7uyjqXBF+0OW8aFtW6kxzQnBdlPXZS/FDFot7wHAsZWrcObJqMqfZFlP/HdKgV0leWYZY70OkFI+bD6u2vx5tFNSW7Lj1TO6m8XOBJYuL9SbuO8rlWuvNuuiH7JD9Uhyxt26NSejxc2PyiJ5rNdQrPKHUmaJL4NIQJLYJ3MZDXV
    USER_ACCOUNT_API_KEY: AgCXD76xs2v0iyrXCcrzRa8NDWW40OoQV1hvlVmVYYN/UGhzOS0ZnsBXjPYD4zE8tFAwA/Izt8RzjuQ9Q7WAzR9+7QuFtcdsnB3bwVGZ72qpWhVZGhQ4n+Xsnc8eUPoDratNmCgx4lBnRYpXyu84z48Rly72MVi7gj1nA1ZflbTnC+HqPLN6vvUvDBrFW37mq9QJZdxGckJccskVHHCBIq82sJlPkIE7ANmjK4wty35peIRN8aGAiOqLyt6Ck/oTLsGvwn7Nv1grjGzrukStyZFp75y2IjEDm+PtVHtPtgRctWaNqb0ABIFI58eUhyUOA0HrKCAGgDvh5OmWLBCM7H53CylaXka2Y2bDq7pW5wV4/cpSsVrq/QwjaqFuwQL+gHKQlPLT2+lM1IRjf3AvbyzgmKDekoEdNRw1qwbMHpep8EZvk8JLvj4rl6+ucI47X5K+2xh7a3mUtqZcWLZVhCFioiNzOR/r5RKIvtQuI0vZwWXry3S/A9hpPxujBMQg3sgsnNV/TO2xrXfmmwFRug53W5ppuS55cvzLxOFUfgLbG6dnRvh+9O6KpWjELU6NGFWfGkR/6qejxlNcYXeduDX/AEqa9CKTjxb5TVewyTTbNlNuy/YJqPyPpvgPotK6pKgPjproWOVTWac46ZS92KCE6B/ZhNDqnCojph0X+TLP3kIGW3C3/UX6d1u85Ci6ZfsZftE/6L+Z/fneMv/bKWgcN8SbtvDxEQxP8FJb3Ko=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-admin-secret
      namespace: ${NAMESPACE}
