apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OAUTH2_PAAS_MPA_ALLOWED_URIS: AgBi8shQHCwRjAaVGWKiZz3Cn+OnOpz+G9Cq5v9bt0yxQhnnOWHM3CZicX2i9yyEIjZQU3Kpqdl32qXxijOSeTSWGu70945bm0vzf9Fk45VuS957iWgFLsEt/tKxzqT4yzWPQ6ugJxa9AoDvvx5BZQ3ocBQT+iItKOzjJXDhcDb/NMYZ/YfcOoNcV/bCkJ/p25AAmiza7Y1TMVJaYbYf0naqWLqbk3vVSTCH4fa6+/VQDVMfMuLZDaYZcV5RSuNmS1SREyvonRDCAwMOqiVyr6XH+ZTvEQTrNUf2VPWJQJ3p1hI8D8HRiAmJeytasbAHNF82wEPAB5xG7VFLIlxdCUXkcJi51jqmGQQwX2cPzPD7oZUC0HiahUjjCLYnyl/O9f68oWdYIJV4FJWa92uUquHPURA/+WWgKHTOGKqkswbIrYm0VqR0CoZ+ziIy4ODYiHnoiflUnr5PP+Ta0Zz73k4PA/Q8J9U3mcvSkmcKHixOwjLPmQHMxjKteX5m6FLkLzYDLyGqcX+PTPRoxeWVonTjFR7hkSRuamXEgNrR/bI9JqIIxgX7Z4xadQo9r05rQcg7Iywa3h1ckNDonqFv6uT7t4oIGuAMxT30onJqzhhjSR7/yhx5hTiiDLP5z65JbqsPun/M2b/odakMZ+9gk8Z6o1O5X5QHypO1EgXJYpAPM6U4C11kN7up/P0b2KVUp81mDfPXa7HDoBt/O50js/lCF1rxNxoGm70TCWVYsK6lDK20QV0pqTcahmyYbm0ES1jsSho=
    OAUTH2_PAAS_MPA_CLIENT_ID: AgADvcUJI6enQ0nMDdi/XiENK3ILdL/1hwoGokskGlmGfljpAi327+yOUDsqKuec28tIVfOQbNm+EOOfghgPdgnGsodfzbPg1f87cZLXa/9mHFrfo1FCfBDqKkx+1+qpc7nRvXJluRYJiAiQyU+HEW4IK4y7tajaVWA/bQIMVn2svucE29Jv6EPMSkI+7MhYga5yeQHQJ3VMO3ihmLg/FxHQTmkSJQ/M5G0ImT/zLHrkdwO4Qm+PhqrTDlZanggKESS8oZK4loaKqYsCbEjpWLtQ0bySE970JtDBWNxA+EcXwHJMBOcD9fbo/rnCOrRTpPuzEODFNcG2YVNatSkZX4tb6EFswru++AkByJfcAKB1X85iqtCribz08as/jz9Lnjzbn4PS+aFGHd49G/sBJ/Nq3+teBedx6daU8O8xqeOPphmDENkQCaDFQ2QBQBAR+L0GXGfeiaxzecDElSySvGbuRKAWQO0OecYiIQTaWn8OyJwcttMvuOR8RjA3sAeNGTp2syZ55nQfYjvADXLoUIv6JP0rL+KmWti5A9/kK0p8EAPmKURJ1k2a4LqvJnBgvLyWRBCdAZ2uqJJH3kBUaKfVmKq6JZ8Qrv188l5qmrEJ650/6ibrLWFBFaPx5870IRZIuW9OBGGiFOEXSmcsKZr4Z+Px4D/bpB0ptnU+w+moTWf2nrbDYkzvywbR7umQPvTPf5+tVrEuYHCWvEVMLV7Edz3v
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
      namespace: ${NAMESPACE}
