apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-admin-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgACtLB11sT4w49kFWYHTpsW12Ym941xZqYzKiyqO42cKVrC7vPhrS46tKyy8+Hm752rBA0m3Dewu41s5Wb/7Ktn24xos/Jwba3NBXbC31v777TdmRfMdV9pFZi/s9tFUQ6xdKlGaeR+Y2qI14/DjompHHNVVy3JDqb8lUu7782DtUuT4ReVOujy4vEM+13SkKlAIEjjtzpqUu6Ty6sizMF0bdOVIECUdiAyP61+LlDasVSBTb98ur2bzq00DttqmxxAaSX6NtwpZkwt9b7ZRSZRQuUrjo07ywAOX6slVsvx8plgOZrEGnsiXG6qlgsOe08cVwIOzbRIz3FxBIejKDl8HHpi8T6GWgN76VrW9F5x4otukUN+6xSEPgJ/YUvXChVGFS1cJlhah9/OzlYgtsJQFSnfYBWITV8QKSfjXunO8ZoOtAwhXEjYyDW5Bu9locsMJNcrFwKskdEgnlummFWiVnY76UPdUAQtDoWjOFM1/Yj/kjvDRv4MjMc6N/Dmf8f+zi3Un1cp9cTykuS2noxt9r+Z7p23vl1zGVvWRGQiocwg8HNMwPI6w24Gw5PiUTFd3rw/fs/FZ5eKklSZRy4sZ/j38wVE8xVUONSrzoKEynN7XZQAhyOkRj66nrBmVw71c0wQcjQ8fUQhgVG0ITm38wVRg27TMautTkEmXwBchvsxj5kIWMsuyAuSG1gw77wFWERPn1QrkHX7l1mHoRaOrTPxs4twYL8=
    USER_ACCOUNT_API_KEY: AgCLpEB3qDrNLOmxARFsr134mdyyK+TkjOBPfT+m6JGaNYX7qHZ2c/KH30qYrB7X2GFLed0FBfhFvodxvaB3qTJ6V8LzjHEh7s16m6y5VksT3lbjCfytX9pDx+xAcGsaJnTF0FwyB/SxKwBL6OpnQPD4X1CVyj37trlOj43Mo9wMBqf8quHyob4plQnodP/aAET2z4pq4PkWqOvyqfLrjKyC1O0ZjhlQo/zmfurYj6+m2uY1+iil2hb0gmcK2V30P1n1XbO4Q97kB1VJ6CW0Rbvc18fA3MDwW9gg48G189XpL9bZfB+VQNRjONcC3OLNIt5YjCTvL8LLo2rHJNQIoniI7N8SGmq2nrqjJSyK0/cnnvdFQZF7SeLPIqL/ZNNkCfbf6AiYBFaP23YoeYOTDp7T3Qnn7KAxjlObqa12YqTmQro5VF0+lZb/9H5Bcq168WEWlQHeyBdZwVT5J6FfhlPfDeKPCBSqv/9DyAmu8UXOKNXrP/135+6195W1z3wyUOdupUzUj+8IG7To19Cc7i9+sC6LYVvza3h0M47Ebfng0BO33cI4tzbvbtTL/zWav0wqXUWh0CKUeTjL25oNtUtN2uscdAZ4Cues9lfdqXAy7zjh5sN/7zyVM1KE0hmp3VVCRpVAf6oYL4T30VsQgNYKjqiEOCACyS/mKzrj2106mgs7sQYFU+i2Mbq663Y00BJQ/JJXePQcAKtHwxDCffxfZJnRehEWDKnNM0uXApk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-admin-secret
      namespace: ${NAMESPACE}
